name: Deploy

on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
